DROP TABLE DEPT CASCADE CONSTRAINTS PURGE;
DROP TABLE EMP CASCADE CONSTRAINTS PURGE;
ALTER TABLE EMP MODIFY(ENAME VARCHAR2(10));
rollback;
ALTER TABLE EMP MODIFY(ENAME VARCHAR2(10));DROP PACKAGE EMP_SAL;
